// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteItemItemIDHandlerFunc turns a function with the right signature into a delete item item Id handler
type DeleteItemItemIDHandlerFunc func(DeleteItemItemIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteItemItemIDHandlerFunc) Handle(params DeleteItemItemIDParams) middleware.Responder {
	return fn(params)
}

// DeleteItemItemIDHandler interface for that can handle valid delete item item Id params
type DeleteItemItemIDHandler interface {
	Handle(DeleteItemItemIDParams) middleware.Responder
}

// NewDeleteItemItemID creates a new http.Handler for the delete item item Id operation
func NewDeleteItemItemID(ctx *middleware.Context, handler DeleteItemItemIDHandler) *DeleteItemItemID {
	return &DeleteItemItemID{Context: ctx, Handler: handler}
}

/* DeleteItemItemID swagger:route DELETE /item/{itemId} deleteItemItemId

delete a item

*/
type DeleteItemItemID struct {
	Context *middleware.Context
	Handler DeleteItemItemIDHandler
}

func (o *DeleteItemItemID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteItemItemIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
