// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutItemHandlerFunc turns a function with the right signature into a put item handler
type PutItemHandlerFunc func(PutItemParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutItemHandlerFunc) Handle(params PutItemParams) middleware.Responder {
	return fn(params)
}

// PutItemHandler interface for that can handle valid put item params
type PutItemHandler interface {
	Handle(PutItemParams) middleware.Responder
}

// NewPutItem creates a new http.Handler for the put item operation
func NewPutItem(ctx *middleware.Context, handler PutItemHandler) *PutItem {
	return &PutItem{Context: ctx, Handler: handler}
}

/* PutItem swagger:route PUT /item putItem

update a item

update a item

*/
type PutItem struct {
	Context *middleware.Context
	Handler PutItemHandler
}

func (o *PutItem) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutItemParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
