// Code generated by go-swagger; DO NOT EDIT.

// Package restapi todo
//
//  Schemes:
//    http
//  Host: localhost:3000
//  BasePath: /
//  Version: 1.0
//  Contact:
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
